// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BsController from "./bs_controller"
application.register("bs", BsController)

import FontAwesomeController from "./font_awesome_controller"
application.register("font-awesome", FontAwesomeController)

import IndexTableController from "./index_table_controller"
application.register("index-table", IndexTableController)

import IntegrationsController from "./integrations_controller"
application.register("integrations", IntegrationsController)

import PagyInitializerController from "./pagy_initializer_controller"
application.register("pagy-initializer", PagyInitializerController)
