// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BsController from "./bs_controller.js"
application.register("bs", BsController)

import FontAwesomeController from "./font_awesome_controller.js"
application.register("font-awesome", FontAwesomeController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import PagyController from "./pagy_controller.js"
application.register("pagy", PagyController)

import SystemTestController from "./system_test_controller.js"
application.register("system-test", SystemTestController)
