services:
  web:
    build:
      context: .
      target: "app"
      args:
        - "RAILS_ENV=${RAILS_ENV:-development}"
        - "NODE_ENV=${NODE_ENV:-development}"
        - "RAILS_STAGING=${RAILS_STAGING:-false}"
    profiles:
      - "web"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - ".env"
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
      DOCKER: true
    ports:
      - "3000:3000"
      - "4000:4000"
    user: ruby:ruby
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    tty: true

  postgres:
    image: postgres:15.2-alpine
    profiles:
      - "postgres"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.9-alpine

  js:
    build:
      context: .
      target: "assets"
    profiles:
      - "assets"
    user: ruby:ruby
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    command: "yarn build --watch"
    tty: true

  css:
    build:
      context: .
      target: "assets"
    profiles:
      - "assets"
    user: ruby:ruby
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    command: "yarn build:css --watch"
    tty: true

  selenium-chrome:
    image: selenium/standalone-chrome
    profiles:
      - "selenium-chrome"
    ports:
      - "5900:5900"
    logging:
      driver: none

volumes:
  db_data:
  gem_cache:
  node_cache:
