version: '3.8'

services:
  web:
    build:
      context: .
      target: "app"
    env_file:
      - .env.development
    depends_on:
      - "postgres"
      - "redis"
    user: ruby:ruby
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    tty: true

  postgres:
    image: postgres:14.5-alpine
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.4-alpine

  js:
    build:
      context: .
      target: "assets"
    user: ruby:ruby
    tty: true
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    command: "yarn build --watch"

  css:
    build:
      context: .
      target: "assets"
    user: ruby:ruby
    tty: true
    volumes:
      - .:/app
      - gem_cache:/gems
      - node_cache:/app/node_modules
    command: "yarn build:css --watch"

  selenium_chrome:
    image: seleniarm/standalone-chromium
    logging:
      driver: none
    ports:
      - "5900:5900"

volumes:
  db_data:
  gem_cache:
  node_cache:
