version: '3.8'

services:
  web:
    image: parsome/blogger:prod
    env_file:
      - .env/production/web
      - .env/production/database
    depends_on:
      - "postgres"
      - "redis"
    user: ruby:ruby
    ports:
      - "80:3000"

  postgres:
    image: postgres:14.5-alpine
    env_file:
      - .env.development
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.4-alpine

volumes:
  db_data:
