version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis

  js:
    build: .
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - gem_cache:/gems
    command: "yarn build --watch"

  css:
    build: .
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
      - gem_cache:/gems
    command: "yarn build:css --watch"

  selenium_chrome:
    image: selenium/standalone-chrome
    logging:
      driver: none
    ports:
      - "5900:5900"
volumes:
  db_data:
  gem_cache:
