x-app: &default-app
  build:
    context: "."
    target: "app"
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
      - "RAILS_ENV=${RAILS_ENV:-development}"
      - "NODE_ENV=${NODE_ENV:-development}"
      - "RAILS_STAGING=${RAILS_STAGING:-false}"
  depends_on:
    - "postgres"
    - "redis"
  env_file:
    - ".env"
  environment:
    DOCKER: true
  user: ruby:ruby
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - ".:/app"
    - gem_cache:/gems
    - node_cache:/app/node_modules

x-assets: &default-assets
  build:
    context: "."
    target: "assets"
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
      - "RAILS_ENV=${RAILS_ENV:-development}"
      - "NODE_ENV=${NODE_ENV:-development}"
  env_file:
    - ".env"
  user: ruby:ruby
  profiles:
    - "assets"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - ".:/app"
    - gem_cache:/gems
    - node_cache:/app/node_modules

x-selenium: &default-selenium
  ports:
    - "5900:5900"
  logging:
    driver: none

services:
  web:
    <<: *default-app
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:3000/up}"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "3000:3000"
      - "4000:4000"
    profiles:
      - "web"

  test:
    <<: *default-app
    depends_on:
      - "postgres"
      - "redis"
      - "selenium-chrome"
    profiles:
      - "test"
    environment:
      - "RAILS_ENV=test"
      - "DOCKER=true"
    command: "bundle exec rspec"

  js:
    <<: *default-assets
    command: "yarn build --watch"

  css:
    <<: *default-assets
    command: "yarn build:css --watch"

  postgres:
    image: postgres:15.2-alpine
    profiles:
      - "postgres"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.9-alpine

  selenium-chrome:
    <<: *default-selenium
    image: selenium/standalone-chrome
    profiles:
      - "selenium-chrome"

  seleniarm-chromium:
    <<: *default-selenium
    image: seleniarm/standalone-chromium
    profiles:
      - "seleniarm-chromium"

volumes:
  db_data:
  gem_cache:
  node_cache:
