default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogger_development
  host: <%= ENV.fetch('POSTGRES_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>

test:
  <<: *default
  database: blogger_test
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>

production:
  <<: *default
  database: blogger_production
  url: <%= ENV['DATABASE_URL'] %>

staging:
  <<: *default
  database: blogger_staging
  host: <%= ENV['IP_ADDRESS_POSTGRES'] %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
