models:
  users: 'users'
  articles: 'newspaper'
  reviews: 'eye'
  comments: 'comments'
actions:
  related: 'share'
  options: 'cogs'
  details: 'info'
  show: 'info'
  edit: 'pen'
  new: 'plus'
  destroy: 'trash'
  archive: 'archive'
  unarchive: 'archive'
  duplicate: 'files-o'
  make_member: 'angle-double-down'
  make_admin: 'angle-double-up'
  impersonate: 'user-o'
  preview: 'eye'
  export: 'download'
  import: 'upload'
  add: 'plus-square'
  search: 'search'
states:
  archived: 'archive'
  in_development: 'code'
  finished: 'check'
