#cloud-config
users:
  - name: ${UNIX_USERNAME}
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdi4UFRRaQqhX+GZ2J3C0MYpxapajvTSHYzfkOrBoP358mS7Ch/0tYj/7OCpFDhosPb+f0twjM3s0AXB1zE+y0XL8AhXvc89p91qFnTt74iTKTWm7BByIqqLyvF8j5ufsVZdSZsPURs11F7QJ41N77NIIQbsX69WJJtTymS7Ut8KJ+vlcL9I4WoBb/oEzGJRjZhkbCwtgRf1ehB8gr5i9km6+GugKEJgzCxixXaBPZjE9NAsG5XIqA4JjY8GrbObcuuVDg5wtFUNkhEEFpvwr4QVgFX7XJCiwL9EMVpYiOwya0gVmBOcJwqR2zzDAt9IXRz1YSI1JpiqCKsDdsJDSGkkjBYZzBp7VhM48+Meda+0djYEJUD7hmBJ94bwvhnTxsA87yHYydkq/7hUwUqc0slyEqj7wDLCJZLkxlCOB+DIfhaQbHELh5+enLMkY64qqyBeiHIxeln7QT7XfNRSBaa5LlT6csYd+K1oc0EO3hTmq9rpCm9+2+/WUC7NBmsH8= jrcech@imac.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC83lI+ctDR8hPiQhxSCRZAqtXMHu/HMQPtEr717Y+v2t7gKyssEkrOGz0OHwKOqf7g2OevcDI1Uh0IG30W5FSDKIhg7zglVmTwvO082FWDZg0qNX+Ew0XCdBbXPjLGInGew2L5982dNht/OWkMLYb2Eua416lZg+AKFuvU88avaRnohvKahmoKDeIu8fLsOP9BScFh+YCXEjg6jTtU5gByxlVom2NAmVc7M34VYMNSEVMzH1u+08bBCJp+ywbHTW3N/ci86FbbnVWxiQj4f2uzWN2roxslA4XpicXrZXgvD5hibf9Wtiqu233YxDRz1fLEdUZoRizZSTxbhnw6qPy82TE8Mxqy0Xv9vVz6aW1cCgdR+3cNdSpt9TJjKwuBxmP9QPUvxNoey86oxfKjK9X+v9T9tb5xZ+tykQgoWcjQFbF+dRpmt+UbJq3abL8eR916tCPBlgdstt/LqR4XLNLFKVku05+GOn6D+YuKBT9YBgG/k1oJYxVDP69kstoxIxk= jrcech@mba238.local

write_files:
  - path: /home/${UNIX_USERNAME}/run/docker_install.sh
    permissions: '0700'
    owner: ${UNIX_USERNAME}:${UNIX_USERNAME}
    encoding: b64
    content: ${DOCKER_INSTALL_CONTENT}
    defer: true

  - path: /home/${UNIX_USERNAME}/run/github_runner_install.sh
    permissions: '0700'
    owner: ${UNIX_USERNAME}:${UNIX_USERNAME}
    encoding: b64
    content: ${GITHUB_RUNNER_INSTALL_CONTENT}
    defer: true

  - path: /home/${UNIX_USERNAME}/run/zsh_install.sh
    permissions: '0700'
    owner: ${UNIX_USERNAME}:${UNIX_USERNAME}
    encoding: b64
    content: ${ZSH_INSTALL_CONTENT}
    defer: true

  - path: /home/${UNIX_USERNAME}/run/prezto_install.sh
    permissions: '0700'
    owner: ${UNIX_USERNAME}:${UNIX_USERNAME}
    encoding: b64
    content: ${PREZTO_INSTALL_CONTENT}
    defer: true

runcmd:
  - ufw allow 'OpenSSH'
  - ufw enable
  - chown -R ${UNIX_USERNAME}:${UNIX_USERNAME} /home/${UNIX_USERNAME}/run
  - sudo -u ${UNIX_USERNAME} /home/${UNIX_USERNAME}/run/docker_install.sh
  - sudo -u ${UNIX_USERNAME} /home/${UNIX_USERNAME}/run/github_runner_install.sh
  - sudo -u ${UNIX_USERNAME} /home/${UNIX_USERNAME}/run/zsh_install.sh
  - sudo -u ${UNIX_USERNAME} /home/${UNIX_USERNAME}/run/prezto_install.sh
